services:
  postgres:
    image: postgres:16-alpine
    container_name: loja-japao-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: loja_japao
      POSTGRES_PASSWORD: loja_japao
      POSTGRES_DB: loja_japao_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
